Add Postgres support to VDI
VEuPathDB/vdi-service pull request #318
Opened 2024-06-28 16:46 UTC by dmgaldi

## Overview
Update AppDB to support postgres

2024-06-28 18:44 UTC, Foxcapades requested changes

2024-06-28 18:44 UTC, Foxcapades commented on lib/app-db/src/main/kotlin/vdi/component/db/app/AppDBPlatform.kt
> +      return entries.find { it.platformString === platformString }
This probably shouldn't be `===`?  If it works like this then it would probably be due to Java's static string pool leading to the input string being a pointer to the same memory address as the enum value, which would likely be broken by runtime configuration.

I suppose it's possible that java will use the static string pool value for the dynamically created/parsed env string as well, however I would be hesitant to count on that behavior without knowing more about it.

2024-06-28 18:44 UTC, Foxcapades commented on lib/app-db/src/main/kotlin/vdi/component/db/app/AppDatabaseRegistry.kt
> +      }
This when could be reduced to 2 branches by either removing the oracle specific string comparison, with oracle going to the `else` block, or more explicitly by changing `when (env.platform)` to `when (AppDBPlatform.fromPlatformString(env.platform))`, however that would introduce the possibility for a null value (which could be elvis-operator-ed into Oracle) in which case the `else` block can be dropped entirely.

2024-06-28 18:44 UTC, Foxcapades commented on lib/app-db/src/main/kotlin/vdi/component/db/app/AppDatabaseRegistry.kt
> +      }
Actually looking further down, the env.platform string value is parsed into a `AppDBPlatform` enum instance later, so perhaps that could just be moved up to a variable?

2024-06-28 18:44 UTC, Foxcapades commented on service/startup.sh
> +waitFor cache-db cache-db "${CACHE_DB_PORT:-5433}"
Without additional changes to the docker-compose files, is this safe to include?

2024-07-01 12:30 UTC, dmgaldi commented on lib/app-db/src/main/kotlin/vdi/component/db/app/AppDBPlatform.kt
> +      return entries.find { it.platformString === platformString }
Oops, I've been a lot of javascript recently

2024-07-01 14:46 UTC, Foxcapades approved these changes

2024-07-01 16:44 UTC, merged