Reconciler module implementation
VEuPathDB/vdi-service pull request #62
Opened 2023-05-30 19:22 UTC by dmgaldi

* Tested synchronization in docker by making reconciler run frequently.
* Didn't test delete yet

2023-06-01 12:57 UTC, Foxcapades requested changes

2023-06-01 18:45 UTC, dmgaldi commented on components/handler-client/src/main/kotlin/org/veupathdb/vdi/lib/handler/client/PluginHandlerClientConfig.kt
> +  val client: HttpClient = HttpClient.newBuilder().build()
None, when I was debugging the plugin hanging I added a timeout here and didn't revert it all the way

2023-06-01 18:45 UTC, dmgaldi commented on components/app-db/src/main/kotlin/org/veupathdb/vdi/lib/db/app/AppDBAccessor.kt
> +  fun streamAllSyncControlRecords(): CloseableIterator<VDISyncControlRecord>
Sounds good, adding in next revision

2023-06-01 18:58 UTC, dmgaldi commented on modules/rest-service/out/production/resources/api.html
I don't know where this came from 🤷

2023-06-01 19:06 UTC, dmgaldi commented on modules/install-trigger-handler/src/main/kotlin/vdi/module/handler/install/data/InstallDataTriggerHandlerImpl.kt
> +    AppDB.withTransaction(projectID) { it.updateSyncControlDataTimestamp(datasetID, s3Dir.getLatestDataTimestamp(OriginTimestamp)) }
Yeah, there's not a good reason to call it twice. Fixed in next revision

2023-06-01 19:09 UTC, dmgaldi commented on modules/install-trigger-handler/src/main/kotlin/vdi/module/handler/install/data/InstallDataTriggerHandlerImpl.kt
> +    updateDataSyncControl(datasetID, projectID, s3Dir)
I think so, otherwise the reconciler would retry indefinitely if an unexpected error kept happening

2023-06-02 19:28 UTC, Foxcapades commented on modules/reconciler/src/main/kotlin/org/veupathdb/vdi/lib/reconciler/CacheDBTarget.kt
> +
Why don't we wipe the dataset record from the cache db?

2023-06-02 19:59 UTC, Foxcapades approved these changes

2023-06-06 17:31 UTC, merged